# Try to find allegro 5 acodec addon
#
# ALLEGRO5_ACODEC_FOUND - system has allegro5 acodec
# ALLEGRO5_ACODEC_INCLUDE_DIR - the allegro5 acodec include directory
# ALLEGRO5_ACODEC_LIBRARIES - Link these to use allegro5 acodec
#

FIND_PATH(ALLEGRO5_ACODEC_INCLUDE_DIR allegro5/allegro_acodec.h)

if (NOT DEFINED DEBUG)
    SET(ALLEGRO5_ACODEC_NAMES ${ALLEGRO5_ACODEC_NAMES} allegro_acodec allegro_acodec.dll)
else ()
    SET(ALLEGRO5_ACODEC_NAMES ${ALLEGRO5_ACODEC_NAMES} allegro_acodec-debug allegro_acodec-debug.dll)
endif ()
FIND_LIBRARY(ALLEGRO5_ACODEC_LIBRARY NAMES ${ALLEGRO5_ACODEC_NAMES})

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_ACODEC DEFAULT_MSG ALLEGRO5_ACODEC_LIBRARY ALLEGRO5_ACODEC_INCLUDE_DIR)

IF(ALLEGRO5_ACODEC_FOUND)
  SET(ALLEGRO5_ACODEC_LIBRARIES ${ALLEGRO5_ACODEC_LIBRARY})
ENDIF(ALLEGRO5_ACODEC_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_ACODEC_LIBRARY ALLEGRO5_ACODEC_INCLUDE_DIR)
