# Try to find allegro 5 audio addon
#
# ALLEGRO5_AUDIO_FOUND - system has allegro5 audio
# ALLEGRO5_AUDIO_INCLUDE_DIR - the allegro5 audio include directory
# ALLEGRO5_AUDIO_LIBRARIES - Link these to use allegro5 audio
#

FIND_PATH(ALLEGRO5_AUDIO_INCLUDE_DIR allegro5/allegro_audio.h)

if (NOT DEFINED DEBUG)
    SET(ALLEGRO5_AUDIO_NAMES ${ALLEGRO5_AUDIO_NAMES} allegro_audio allegro_audio.dll)
else ()
    SET(ALLEGRO5_AUDIO_NAMES ${ALLEGRO5_AUDIO_NAMES} allegro_audio-debug allegro_audio-debug.dll)
endif ()
FIND_LIBRARY(ALLEGRO5_AUDIO_LIBRARY NAMES ${ALLEGRO5_AUDIO_NAMES})

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_AUDIO DEFAULT_MSG ALLEGRO5_AUDIO_LIBRARY ALLEGRO5_AUDIO_INCLUDE_DIR)

IF(ALLEGRO5_AUDIO_FOUND)
  SET(ALLEGRO5_AUDIO_LIBRARIES ${ALLEGRO5_AUDIO_LIBRARY})
ENDIF(ALLEGRO5_AUDIO_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_AUDIO_LIBRARY ALLEGRO5_AUDIO_INCLUDE_DIR)
