# Try to find allegro 5 image addon
#
# ALLEGRO5_IMAGE_FOUND - system has allegro5 image
# ALLEGRO5_IMAGE_INCLUDE_DIR - the allegro5 image include directory
# ALLEGRO5_IMAGE_LIBRARIES - Link these to use allegro5 image
#

FIND_PATH(ALLEGRO5_IMAGE_INCLUDE_DIR allegro5/allegro_image.h)

if (NOT DEFINED DEBUG)
    SET(ALLEGRO5_IMAGE_NAMES ${ALLEGRO5_IMAGE_NAMES} allegro_image allegro_image.dll)
else ()
    SET(ALLEGRO5_IMAGE_NAMES ${ALLEGRO5_IMAGE_NAMES} allegro_image-debug allegro_image-debug.dll)
endif ()
FIND_LIBRARY(ALLEGRO5_IMAGE_LIBRARY NAMES ${ALLEGRO5_IMAGE_NAMES})

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_IMAGE DEFAULT_MSG ALLEGRO5_IMAGE_LIBRARY ALLEGRO5_IMAGE_INCLUDE_DIR)

IF(ALLEGRO5_IMAGE_FOUND)
  SET(ALLEGRO5_IMAGE_LIBRARIES ${ALLEGRO5_IMAGE_LIBRARY})
ENDIF(ALLEGRO5_IMAGE_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_IMAGE_LIBRARY ALLEGRO5_IMAGE_INCLUDE_DIR)
