# Try to find allegro 5 primitives addon
#
# ALLEGRO5_PRIMITIVES_FOUND - system has allegro5 primitives
# ALLEGRO5_PRIMITIVES_INCLUDE_DIR - the allegro5 primitives include directory
# ALLEGRO5_PRIMITIVES_LIBRARIES - Link these to use allegro5 primitives
#

FIND_PATH(ALLEGRO5_PRIMITIVES_INCLUDE_DIR allegro5/allegro_primitives.h)

if (NOT DEFINED DEBUG)
    SET(ALLEGRO5_PRIMITIVES_NAMES ${ALLEGRO5_PRIMITIVES_NAMES} allegro_primitives allegro_primitives.dll)
else ()
    SET(ALLEGRO5_PRIMITIVES_NAMES ${ALLEGRO5_PRIMITIVES_NAMES} allegro_primitives-debug allegro_primitives-debug.dll)
endif ()
FIND_LIBRARY(ALLEGRO5_PRIMITIVES_LIBRARY NAMES ${ALLEGRO5_PRIMITIVES_NAMES})

# handle the QUIETLY and REQUIRED arguments and set ALLEGRO5_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLEGRO5_PRIMITIVES DEFAULT_MSG ALLEGRO5_PRIMITIVES_LIBRARY ALLEGRO5_PRIMITIVES_INCLUDE_DIR)

IF(ALLEGRO5_PRIMITIVES_FOUND)
  SET(ALLEGRO5_PRIMITIVES_LIBRARIES ${ALLEGRO5_PRIMITIVES_LIBRARY})
ENDIF(ALLEGRO5_PRIMITIVES_FOUND)

MARK_AS_ADVANCED(ALLEGRO5_PRIMITIVES_LIBRARY ALLEGRO5_PRIMITIVES_INCLUDE_DIR)
